// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QPU_DataAccess.Models;

#nullable disable

namespace QPU_DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260408000000_AddBestEmployeeUniqueIndex")]
    partial class AddBestEmployeeUniqueIndex { protected override void BuildTargetModel(ModelBuilder modelBuilder) { } }
}
