// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using QPU_DataAccess.Models;

#nullable disable

namespace QPU_DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260406000000_AddFacultyIdToAppUser")]
    partial class AddFacultyIdToAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
