// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QPU_DataAccess.Models;

#nullable disable

namespace QPU_DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260409000000_AddIsSuperAdminToAppUser")]
    partial class AddIsSuperAdminToAppUser { protected override void BuildTargetModel(ModelBuilder modelBuilder) { } }
}
